#!/usr/bin/env bash
if [ "$2" == "clone" ]; then
  git clone https://github.com/techspot/zendframework1_docker.git $1 && cd $1;
fi

sudo chmod u+x ./*

if [ "$(uname)" == "Darwin" ] || [ "$(uname)" == "cygwin" ] || [ "$(uname)" == "msys" ] || [ "$(uname)" == "win32" ]; then
  git checkout -f mac;
  sed -i '' -e "s/<project_name>/$1/g" docker-compose.yml \
  && sed -i '' -e "s/<project_name>/$1/g" docker-sync.yml
else
  git checkout -f master;
  sed -i '' -e "s/<project_name>/$1/g" docker-compose.yml;
fi

if [ ! -e src/public/index.php ]; then
  echo "<?php phpinfo();" > src/public/index.php;
fi

bash start
